### ISSUE TITLE
Generate Random initial positions for Musketeer Chess Variant

### ISSUE THREAD

**Issue by musketeerchess** [joakim/fischer960#1]
Hi, I'm Zied, a Medical Doctor from France.
I invented Musketeer Chess variant, a variant involving new pieces different from the classic pieces, that are Added on fantom squares on Row 0 and 9. 
The new pieces are chosen by pairs (making it possible to have 45 different combinations) and these pieces will be introduced once one of the pieces in the first row move for the first time. The introduction of the new pieces is precised before the game begins (= Gating Selection).

For example, the two additional pieces chosen to begin the game are Archbishop and Chancellor.

White will place the Archbishop on b0 fantom square and the Chancellor on d0 square. This means that when the knight b1 moves for the first time, the Archbishop waiting on b0 square will "gate" = will be place inside the board on b1 square left vacant by the knight. The same happens when the Queen moves for the first time allowing the Chancellor to be gated.

Only restriction, the pieces waiting to be gated cannot remain waiting behind a King and a Rook at the same time to avoid gating both pieces at the same time when castling.

The additional pieces are:
* Leopard L
* Cannon C
* Archbishop A
* Chancellor M
* Hawk H
* Elephant E
* Dragon D
* Spider S
* Unicorn U
* Fortress F

the rules for Musketeer Chess can be found here: 
https://github.com/fsmosca/musketeer-chess

Here is the Musketeer Stockfish engine based on Stockfish
https://github.com/ianfab/Musketeer-Stockfish

Thanks for your help
Zied

**Comment by joakim** [comment]
That's an interesting variant!

This library is only for Fischer random, however, I don't plan to add support for other variants. But you are more than welcome to fork my code and modify it to support Musketeer Chess. The MIT license allows this. I don't have time to do so myself, but I'd be happy to answer any questions :)
